name: flutter_main
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  url_strategy: ^0.2.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  equatable: ^2.0.3
  gql: ^0.13.1-alpha
  artemis: '>=7.0.0 <8.0.0' # only if you're using ArtemisClient!

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/.env

  # ttf or otf only
  # fonts:
    # - family: hoge
    #   fonts:
    #     - asset: fonts/hoge.ttf
